### ISSUE TITLE
Size

### ISSUE THREAD

**Issue by VitaliyAT** [Benisgo/Symbolic11#1]
Why it's so huge? For opersations that can be done in one command line - it tool more then 100Mb after unzip... ? On AutoIT compilling in EXE it take less then 100kb... 

Could you reduce size of program?

**Comment by Benisgo** [comment]
To be honest with you I have no clue since this was my first project with using visual studio
I've tried a bunch of different attempts at decreasing the size but visual studio still builds it with every single .dll under the sun
If you do know how to lower the size please let me know
